# Generated by Django 4.2.7 on 2023-11-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(default=10000, max_length=200000)),
                ('color', models.CharField(default='oq', max_length=20)),
                ('year', models.CharField(default='2000', max_length=30)),
            ],
        ),
    ]
